
Epoch: 0 Accuracy: 12
  0%|                                                                | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    wandb({
TypeError: 'module' object is not callable